// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA341LH9ej7QYg3XGbFjiF_WNQaUI2ZGYg',
    appId: '1:70073551359:web:967383cd90041233f23fca',
    messagingSenderId: '70073551359',
    projectId: 'property-app-c3569',
    authDomain: 'property-app-c3569.firebaseapp.com',
    storageBucket: 'property-app-c3569.firebasestorage.app',
    measurementId: 'G-77ZTEFSV6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1tLfkDQ4dsquOExp3gVXAU2V-NEJz4oc',
    appId: '1:70073551359:android:ddde702efbfeb2d9f23fca',
    messagingSenderId: '70073551359',
    projectId: 'property-app-c3569',
    storageBucket: 'property-app-c3569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJHGwMebQ2BVh0DIMBEZl2JuW_fzQ5w4',
    appId: '1:70073551359:ios:cc970fcc9eaf05d0f23fca',
    messagingSenderId: '70073551359',
    projectId: 'property-app-c3569',
    storageBucket: 'property-app-c3569.firebasestorage.app',
    iosBundleId: 'com.example.propertyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJHGwMebQ2BVh0DIMBEZl2JuW_fzQ5w4',
    appId: '1:70073551359:ios:cc970fcc9eaf05d0f23fca',
    messagingSenderId: '70073551359',
    projectId: 'property-app-c3569',
    storageBucket: 'property-app-c3569.firebasestorage.app',
    iosBundleId: 'com.example.propertyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA341LH9ej7QYg3XGbFjiF_WNQaUI2ZGYg',
    appId: '1:70073551359:web:a69911d39de52627f23fca',
    messagingSenderId: '70073551359',
    projectId: 'property-app-c3569',
    authDomain: 'property-app-c3569.firebaseapp.com',
    storageBucket: 'property-app-c3569.firebasestorage.app',
    measurementId: 'G-CEFV0T03L3',
  );

}